---
title: "Homework 4 Problem 2"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

I choose Instacart dataset in p8105.datasets package
```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(p8105.datasets)
library(tidyverse)
```

```{r}
data("instacart", package = "p8105.datasets")
instacart_sample <- 
  instacart |>
  sample_n(3000) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatter Plot of Order Hour vs. Add to Cart Order

```{r}
scatter_data = instacart_sample |> 
  filter(aisle %in% c("fresh fruits", "fresh vegetables"))

scatter_plot = plot_ly(scatter_data, x = ~order_hour_of_day, y = ~add_to_cart_order, 
                        color = ~aisle, mode = 'markers', type = 'scatter') |>
  layout(title = "Order Hour of Day vs Add to Cart Order",
         xaxis = list(title = "Order Hour of Day"),
         yaxis = list(title = "Add to Cart Order"))
scatter_plot
```

Column {data-width=350}
-----------------------------------------------------------------------

### Top 10 Aisles by Frequency

```{r}
aisle_counts <- instacart_sample %>%
  count(aisle, sort = TRUE) %>%
  top_n(10, n)

bar_plot <- plot_ly(aisle_counts, x = ~reorder(aisle, n), y = ~n, type = 'bar') %>%
  layout(title = "Top 10 Aisles by Frequency",
         xaxis = list(title = "Aisle", tickangle = -45),
         yaxis = list(title = "Count"))
bar_plot
```

### Box Plot of Add to Cart Order by Aisle

```{r}
box_data <- instacart_sample %>%
  filter(aisle %in% c("fresh fruits", "fresh vegetables", "yogurt", "packaged vegetables fruits"))

box_plot <- plot_ly(box_data, x = ~aisle, y = ~add_to_cart_order, type = 'box') %>%
  layout(title = "Add to Cart Order by Aisle",
         xaxis = list(title = "Aisle"),
         yaxis = list(title = "Add to Cart Order"))
box_plot
```

